server.port: 9090

# DB CONNECTION
spring.datasource.url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=public
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.username: postgres
spring.datasource.password: postgres

# liquibase
spring.liquibase.change-log: classpath:liquibase.xml
log4j.logger.org.springframework.transaction: INFO